# fly.toml 최종 버전

app = 'hearth-chat'
primary_region = 'nrt'

[build]
  image = 'gigabitamin/hearth-chat:latest'

[deploy]
  release_command = "sh -c 'python manage.py migrate --noinput && python manage.py collectstatic --noinput'"
  strategy = 'immediate'

[env]
  DJANGO_SETTINGS_MODULE = 'hearth_chat.settings'
  IS_FLY_DEPLOY = 'true'
  PORT = '8080'

# [추가] app 프로세스가 실행할 명령어를 명확하게 지정
[processes]
  app = "/entrypoint.sh" # Dockerfile의 ENTRYPOINT 대신 여기서 직접 지정

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[machines]
  app = { size = "shared-cpu-2x" }