app = "hearth-redis"
primary_region = "nrt"

[build]
  image = "redis:7-alpine"

[env]
  PORT = "6379"

[[services]]
  protocol = "tcp"
  internal_port = 6379
  processes = ["app"]

  [[services.ports]]
    port = 6379
    handlers = ["tcp"]

[[vm]]
  memory_mb = 256
  cpus = 1