# Generated by Django 5.0.1 on 2025-07-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_notificationread"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="max_members",
            field=models.PositiveIntegerField(default=4, verbose_name="최대 인원수"),
        ),
    ]
