# Generated by Django 5.0.1 on 2025-07-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_chatroom_max_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="question_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_responses",
                to="chat.chat",
                verbose_name="AI 응답을 유발한 질문 메시지",
            ),
        ),
    ]
