# Generated by Django 5.0.1 on 2025-08-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_add_ai_settings_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="imageUrls",
            field=models.TextField(
                blank=True, null=True, verbose_name="다중 이미지 URL 배열 (JSON)"
            ),
        ),
    ]
