# Generated by Django 5.0.1 on 2025-08-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_add_ai_model_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="tts_pitch",
            field=models.FloatField(default=1.0, verbose_name="TTS 음조"),
        ),
    ]
