# Generated by Django 5.0.1 on 2025-08-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_usersettings_ai_avatar_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="face_tracking_enabled",
            field=models.BooleanField(default=False, verbose_name="얼굴 트래킹 활성화"),
        ),
    ]
