# Generated by Django 5.0.1 on 2025-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_usersettings_face_tracking_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="camera_enabled",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="face_tracking_enabled",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="camera_settings",
            field=models.TextField(
                blank=True,
                default='{"enabled": false, "face_tracking_enabled": false, "tracking_sensitivity": 0.5, "tracking_smoothness": 0.3, "auto_tracking_enabled": true, "tracking_camera_index": 0}',
                null=True,
                verbose_name="카메라 설정 (JSON)",
            ),
        ),
    ]
