# Generated by Django 5.0.1 on 2025-08-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0017_remove_usersettings_camera_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_video_call",
            field=models.BooleanField(default=False, verbose_name="화상채팅 여부"),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="video_call_status",
            field=models.CharField(
                choices=[("waiting", "대기 중"), ("active", "통화 중"), ("ended", "통화 종료")],
                default="waiting",
                max_length=20,
                verbose_name="화상채팅 상태",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("ai", "AI 채팅"),
                    ("user", "1:1 개인 채팅"),
                    ("group", "그룹 채팅"),
                    ("public", "공개 오픈 채팅"),
                    ("voice", "음성 통화"),
                    ("video_call", "1:1 화상채팅"),
                ],
                max_length=10,
                verbose_name="대화방 타입",
            ),
        ),
    ]
