# Generated by Django 5.0.1 on 2025-07-11 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("user", "사용자"), ("ai", "AI")],
                        max_length=10,
                        verbose_name="메시지 타입",
                    ),
                ),
                ("content", models.TextField(verbose_name="메시지 내용")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="전송 시간"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="세션 ID"
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="감정 상태"
                    ),
                ),
                (
                    "attach_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="image/chat_attach/",
                        verbose_name="첨부 이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "verbose_name_plural": "채팅 메시지들",
                "db_table": "chat_chat",
                "ordering": ["timestamp"],
            },
        ),
    ]
