# Generated by Django 5.0.1 on 2025-07-12 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="대화방 이름")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("ai", "AI 채팅"),
                            ("user", "사용자 채팅"),
                            ("group", "그룹 채팅"),
                            ("voice", "음성 통화"),
                        ],
                        max_length=10,
                        verbose_name="대화방 타입",
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="AI 제공자"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 상태")),
                (
                    "is_voice_call",
                    models.BooleanField(default=False, verbose_name="음성 통화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
            ],
            options={
                "verbose_name": "대화방",
                "verbose_name_plural": "대화방들",
                "db_table": "chat_chatroom",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="발신자",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="message_type",
            field=models.CharField(
                choices=[("user", "사용자"), ("ai", "AI"), ("system", "시스템")],
                max_length=10,
                verbose_name="메시지 타입",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chatroom",
                verbose_name="대화방",
            ),
        ),
        migrations.CreateModel(
            name="ChatRoomParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_owner", models.BooleanField(default=False, verbose_name="방장 여부")),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="참여 시간"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.chatroom",
                        verbose_name="대화방",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "대화방 참여자",
                "verbose_name_plural": "대화방 참여자들",
                "db_table": "chat_chatroomparticipant",
                "unique_together": {("room", "user")},
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                through="chat.ChatRoomParticipant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="참여자들",
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tts_enabled",
                    models.BooleanField(default=True, verbose_name="TTS 활성화"),
                ),
                (
                    "tts_voice",
                    models.CharField(
                        default="ko-KR", max_length=50, verbose_name="TTS 음성"
                    ),
                ),
                ("tts_speed", models.FloatField(default=1.0, verbose_name="TTS 속도")),
                (
                    "voice_recognition_enabled",
                    models.BooleanField(default=True, verbose_name="음성 인식 활성화"),
                ),
                (
                    "auto_send_enabled",
                    models.BooleanField(default=True, verbose_name="자동 전송 활성화"),
                ),
                (
                    "voice_confidence_threshold",
                    models.FloatField(default=0.7, verbose_name="음성 인식 신뢰도 임계값"),
                ),
                (
                    "camera_enabled",
                    models.BooleanField(default=False, verbose_name="카메라 활성화"),
                ),
                (
                    "ai_avatar_enabled",
                    models.BooleanField(default=True, verbose_name="AI 아바타 활성화"),
                ),
                (
                    "user_avatar_enabled",
                    models.BooleanField(default=False, verbose_name="사용자 아바타 활성화"),
                ),
                (
                    "theme",
                    models.CharField(default="dark", max_length=20, verbose_name="테마"),
                ),
                (
                    "language",
                    models.CharField(default="ko", max_length=10, verbose_name="언어"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 설정",
                "verbose_name_plural": "사용자 설정들",
                "db_table": "chat_usersettings",
            },
        ),
        migrations.CreateModel(
            name="VoiceCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "대기 중"),
                            ("active", "통화 중"),
                            ("ended", "종료"),
                            ("missed", "부재중"),
                        ],
                        default="waiting",
                        max_length=10,
                        verbose_name="통화 상태",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작 시간"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="종료 시간"),
                ),
                ("duration", models.IntegerField(default=0, verbose_name="통화 시간(초)")),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="발신자",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수신자",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.chatroom",
                        verbose_name="대화방",
                    ),
                ),
            ],
            options={
                "verbose_name": "음성 통화",
                "verbose_name_plural": "음성 통화들",
                "db_table": "chat_voicecall",
            },
        ),
    ]
