# Generated by Django 5.0.1 on 2025-07-16 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="답장 시간"),
                ),
                (
                    "original_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="chat.chat",
                        verbose_name="원본 메시지",
                    ),
                ),
                (
                    "reply_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_to",
                        to="chat.chat",
                        verbose_name="답장 메시지",
                    ),
                ),
            ],
            options={
                "verbose_name": "메시지 답장",
                "verbose_name_plural": "메시지 답장들",
                "db_table": "chat_messagereply",
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=10, verbose_name="이모지")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="반응 시간"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chat.chat",
                        verbose_name="메시지",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "메시지 반응",
                "verbose_name_plural": "메시지 반응들",
                "db_table": "chat_messagereaction",
                "unique_together": {("message", "user", "emoji")},
            },
        ),
        migrations.CreateModel(
            name="PinnedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="고정 시간"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.chat",
                        verbose_name="고정된 메시지",
                    ),
                ),
                (
                    "pinned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="고정한 사용자",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_messages",
                        to="chat.chatroom",
                        verbose_name="대화방",
                    ),
                ),
            ],
            options={
                "verbose_name": "고정된 메시지",
                "verbose_name_plural": "고정된 메시지들",
                "db_table": "chat_pinnedmessage",
                "unique_together": {("room", "message")},
            },
        ),
    ]
