# Generated by Django 5.0.1 on 2025-07-16 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=10, verbose_name="이모지")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="반응 시간"),
                ),
            ],
            options={
                "verbose_name": "메시지 반응",
                "verbose_name_plural": "메시지 반응들",
                "db_table": "chat_messagereaction",
            },
        ),
        migrations.CreateModel(
            name="MessageReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="답장 시간"),
                ),
            ],
            options={
                "verbose_name": "메시지 답장",
                "verbose_name_plural": "메시지 답장들",
                "db_table": "chat_messagereply",
            },
        ),
        migrations.CreateModel(
            name="PinnedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="고정 시간"),
                ),
            ],
            options={
                "verbose_name": "고정된 메시지",
                "verbose_name_plural": "고정된 메시지들",
                "db_table": "chat_pinnedmessage",
            },
        ),
        migrations.AlterField(
            model_name="chat",
            name="content",
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["room", "timestamp"], name="chat_chat_room_id_3784b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["sender_type", "timestamp"], name="chat_chat_sender__335aa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["username"], name="chat_chat_usernam_f20540_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["created_at"], name="chat_chat_created_68fe70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["room_type", "is_public"], name="chat_chatro_room_ty_c15654_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["is_active", "updated_at"],
                name="chat_chatro_is_acti_3dedb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["name"], name="chat_chatro_name_b0f383_idx"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["created_at"], name="chat_chatro_created_914abe_idx"
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="chat.chat",
                verbose_name="메시지",
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="messagereply",
            name="original_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="chat.chat",
                verbose_name="원본 메시지",
            ),
        ),
        migrations.AddField(
            model_name="messagereply",
            name="reply_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply_to",
                to="chat.chat",
                verbose_name="답장 메시지",
            ),
        ),
        migrations.AddField(
            model_name="pinnedmessage",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chat",
                verbose_name="고정된 메시지",
            ),
        ),
        migrations.AddField(
            model_name="pinnedmessage",
            name="pinned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="고정한 사용자",
            ),
        ),
        migrations.AddField(
            model_name="pinnedmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pinned_messages",
                to="chat.chatroom",
                verbose_name="대화방",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("message", "user", "emoji")},
        ),
        migrations.AlterUniqueTogether(
            name="pinnedmessage",
            unique_together={("room", "message")},
        ),
    ]
