# Generated by Django 5.0.1 on 2025-07-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatroom_chat_sender_alter_chat_message_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="공개 방 여부"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="대화방 이름"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("ai", "AI 채팅"),
                    ("user", "1:1 개인 채팅"),
                    ("group", "그룹 채팅"),
                    ("public", "공개 오픈 채팅"),
                    ("voice", "음성 통화"),
                ],
                max_length=10,
                verbose_name="대화방 타입",
            ),
        ),
    ]
