# Generated by Django 5.0.1 on 2025-07-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chat_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="content",
            field=models.TextField(verbose_name="메시지 내용"),
        ),
    ]
