# Generated by Django 5.0.1 on 2025-07-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chat_emotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_images/", verbose_name="첨부 이미지"
            ),
        ),
    ]
