# Generated by Django 5.0.1 on 2025-07-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatroom_is_public_alter_chatroom_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="ai_response_enabled",
            field=models.BooleanField(default=True, verbose_name="AI 응답 활성화"),
        ),
    ]
