# Generated by Django 5.0.1 on 2025-07-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_chatroom_ai_response_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="attach_image",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="첨부 이미지 URL"
            ),
        ),
    ]
