# Generated by Django 5.0.1 on 2025-07-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_change_attach_image_to_charfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
