# Generated by Django 5.0.1 on 2025-07-25 00:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_mediafile"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
