# Generated by Django 5.0.1 on 2025-08-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_usersettings_tts_pitch"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="ai_avatar_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="AI 아바타 URL"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="user_avatar_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="사용자 아바타 URL"
            ),
        ),
    ]
