# Generated by Django 5.0.1 on 2025-07-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_messagefavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="ai_response_enabled",
            field=models.BooleanField(default=False, verbose_name="AI 응답 활성화"),
        ),
    ]
