# Generated by Django 5.0.1 on 2025-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="content",
            field=models.TextField(
                db_collation="utf8mb4_unicode_ci", verbose_name="메시지 내용"
            ),
        ),
        migrations.AlterModelTable(
            name="chat",
            table="chat_chat",
        ),
    ]
