# Generated by Django 5.0.1 on 2025-07-09 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_chat_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="image",
            new_name="attach_image",
        ),
    ]
