# Generated by Django 5.0.1 on 2025-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_rename_image_chat_attach_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="attach_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="image/chat_attach/",
                verbose_name="첨부 이미지",
            ),
        ),
    ]
