# .github/workflows/cloudtype-deploy.yml
name: Deploy to Cloudtype
on:
  push:
    branches:
      - main    
    paths:
      - 'hearth_chat_django/**'
      - 'hearth_chat_react/**'
      - 'Dockerfile'
      - '.github/workflows/cloudtype-deploy.yml'
jobs:
  deploy:
    name: Deploy app    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - uses: cloudtype-github-actions/deploy@v1
        env:
          CLOUDTYPE_API_TOKEN: ${{ secrets.CLOUDTYPE_API_TOKEN }}
        with:          
          project: gbrabbit/hearth_chat
          service: hearth-chat
          wait: true     