# .github/workflows/cloudtype-deploy.yml

name: Deploy to Cloudtype

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: cloudtype-deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Cloudtype
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_API_KEY }}
          project: 'gbrabbit/hearth_chat'
          yaml: |
            name: hearth-chat
            app: dockerfile
            resources:
              spot: true
              memory: 0.5
            options:
              git:
                url: https://github.com/gigabitamin/hearth_chat
                ref: main
              ports: "8080"
              commands: /entrypoint.sh
