# .github/workflows/cloudtype-deploy.yml

# 워크플로우의 이름을 지정합니다. GitHub Actions 탭에 이 이름이 표시됩니다.
name: Deploy to Cloudtype

# 워크플로우가 실행될 시점을 지정합니다.
on:
  push:
    branches:
      - main  # 'main' 브랜치에 push 이벤트가 발생했을 때만 실행됩니다.

# 워크플로우에서 실행될 작업(job)들을 정의합니다.
jobs:
  deploy:
    # 작업이 실행될 가상 환경을 지정합니다. 최신 Ubuntu를 사용합니다.
    runs-on: ubuntu-latest

    # 작업의 단계(step)들을 정의합니다.
    steps:
      # 1. 코드 체크아웃
      # GitHub 저장소의 코드를 가상 환경으로 가져옵니다.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cloudtype에 배포
      # Cloudtype이 공식적으로 제공하는 GitHub Action을 사용합니다.
      - name: Deploy to Cloudtype
        uses: cloudtype-github-actions/deploy@v1
        with:
          # GitHub Secrets에 저장해 둔 Cloudtype API 토큰을 사용합니다.
          token: ${{ secrets.CLOUDTYPE_API_KEY }}
          
          # 배포할 프로젝트를 지정합니다.
          project: 'gbrabbit/hearth_chat'
          
          # ✅ 'file' 대신 'yaml' 파라미터를 사용하여 배포 정보를 직접 전달합니다.
          yaml: |
            name: hearth-chat
            app: dockerfile
