# Generated by Django 5.0.1 on 2025-07-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chat_content_alter_chat_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="emotion",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="감정 상태"
            ),
        ),
    ]
